// List of cognitive biases, grouped using Wikipedia's functional taxonomy.
// Source: https://en.wikipedia.org/wiki/List_of_cognitive_biases
// Duplicate biases (same name appearing under multiple groupings) are kept once.

export type Bias = { id: string; name: string; description: string }
export type Category = { name: string; biases: Bias[] }

type RawCategory = { name: string; biases: [string, string][] }

const RAW: RawCategory[] = [
  {
    name: 'Estimation',
    biases: [
      ['Aesthetic–usability effect', 'Perceiving attractive things as more usable.'],
      ['Attribute substitution', 'Substituting an easily calculated heuristic for a complex judgment.'],
      ['Availability heuristic', 'Overestimating the likelihood of events that come to mind easily.'],
      ['Conjunction fallacy', 'Assuming specific conditions are more probable than a single general one.'],
      ['Hot-cold empathy gap', 'Underestimating how much visceral drives influence attitudes and behaviour.'],
      ['Tachypsychia', 'Time perception lengthening or contracting under stress.'],
      ['Time-saving bias', 'Misjudging the time saved when changing speed.'],
      ['Travis syndrome', 'Overestimating the significance of the present.'],
      ['Anchoring bias', 'Over-relying on the first piece of information when deciding.'],
      ['Base rate fallacy', 'Ignoring general information in favour of case-specific detail.'],
      ['Dunning–Kruger effect', 'The unskilled overestimate ability; experts underestimate it.'],
      ["Gambler's fallacy", 'Believing past events change the odds of unchanging future ones.'],
      ['Hard–easy effect', 'Overestimating ability on hard tasks, underestimating on easy ones.'],
      ['Hot-hand fallacy', 'Believing a streak of success raises the chance of more.'],
      ['Insensitivity to sample size', 'Under-expecting variation in small samples.'],
      ['Interoceptive bias', 'Bodily sensations distorting judgments about external matters.'],
      ['Conservatism bias', 'Insufficiently revising beliefs when shown new evidence.'],
      ['Subadditivity effect', 'Judging the whole probability as less than the sum of its parts.'],
      ['Systematic bias', 'Judgment errors from non-equivalent regression effects.'],
      ['Unit bias', 'Perceiving a standard portion as the appropriate amount.'],
      ['Weber–Fechner law', 'Difficulty perceiving small differences in large quantities.'],
      ['Exaggerated expectation', 'Expecting outcomes more extreme than those that occur.'],
      ['Hedonic recall bias', 'Mis-estimating earnings based on satisfaction.'],
      ['Illusion of validity', 'Overestimating the accuracy of one’s judgments.'],
      ['Impact bias', 'Overestimating the length or intensity of future emotions.'],
      ['Outcome bias', 'Judging a decision by its outcome rather than its quality.'],
      ['Planning fallacy', 'Underestimating how long a task will take.'],
      ['Restraint bias', 'Overestimating one’s ability to resist temptation.'],
      ['Sexual overperception bias', 'Overestimating others’ sexual interest.'],
      ['Sexual underperception bias', 'Underestimating others’ sexual interest.'],
      ['Curse of knowledge', 'Struggling to think from a less-informed perspective.'],
      ['Extrinsic incentives bias', 'Seeing others as situationally motivated, oneself as intrinsically.'],
      ['False consensus effect', 'Overestimating how much others share your views.'],
      ['Illusion of transparency', 'Overestimating how well others know your mental state.'],
      ['Naïve cynicism', 'Expecting more egocentrism in others than in oneself.'],
      ['Optimism bias', 'Being over-optimistic about favourable outcomes.'],
      ['Outgroup homogeneity bias', 'Seeing other groups as less varied than one’s own.'],
      ['Pessimism bias', 'Overestimating the likelihood of bad outcomes.'],
      ['Spotlight effect', 'Overestimating how much others notice you.'],
      ['Worse-than-average effect', 'Believing oneself worse than others at hard tasks.'],
    ],
  },
  {
    name: 'Decision-making',
    biases: [
      ['Ambiguity effect', 'Avoiding options whose favourable odds are unknown.'],
      ['Authority bias', 'Attributing greater accuracy to an authority’s opinion.'],
      ['Automation bias', 'Depending excessively on automated systems.'],
      ['Default effect', 'Favouring the default option among choices.'],
      ['Dread aversion', 'Dread carrying double the emotional weight of savouring.'],
      ['Framing effect', 'Drawing different conclusions from the same information framed differently.'],
      ['Hyperbolic discounting', 'Preferring immediate payoffs over larger delayed ones.'],
      ['Compassion fade', 'Feeling more compassion for one victim than for many.'],
      ['Loss aversion', 'The pain of a loss outweighing the pleasure of an equal gain.'],
      ['Neglect of probability', 'Disregarding probability under uncertainty.'],
      ['Non-adaptive choice switching', 'Avoiding a previously optimal choice after a bad outcome.'],
      ['Prevention bias', 'Seeing spending on prevention as more secure than on detection.'],
      ['Pseudocertainty effect', 'Risk-averse for good outcomes, risk-seeking for bad ones.'],
      ['Risk compensation', 'Taking bigger risks when feeling safer.'],
      ['Zero-risk bias', 'Preferring to eliminate a small risk over a larger reduction.'],
      ['Action bias', 'Acting on a problem even when inaction would be better.'],
      ['Additive bias', 'Solving problems by adding when subtracting would be better.'],
      ['Decoy effect', 'Preferences shifting when an inferior option is introduced.'],
      ['Ballot order effect', 'Candidates listed first receiving more votes.'],
      ['Cheerleader effect', 'People appearing more attractive in a group than alone.'],
      ['Compromise effect', 'Choices swayed by being framed as extreme or average.'],
      ['Denomination effect', 'Spending more when money is in small denominations.'],
      ['Disposition effect', 'Selling winners and clinging to losers.'],
      ['Distinction bias', 'Seeing jointly evaluated options as more different than they are.'],
      ['Less-is-better effect', 'Preferring a smaller set when judged separately.'],
      ['Money illusion', 'Focusing on nominal value rather than purchasing power.'],
      ['Phantom effect', 'Choices swayed by a dominant but unavailable option.'],
      ['Normalcy bias', 'Refusing to plan for an unprecedented disaster.'],
      ['Projection bias', 'Overestimating how stable one’s future preferences are.'],
      ['Scope neglect', 'Insensitivity to the size of a problem when evaluating it.'],
      ['Doubling-back aversion', 'Avoiding retracing steps even when it saves effort.'],
      ['Endowment effect', 'Demanding more to give up something than you’d pay for it.'],
      ['Escalation of commitment', 'Increasing investment despite mounting contrary evidence.'],
      ['Functional fixedness', 'Limiting an object to its traditional use.'],
      ['Mere exposure effect', 'Liking things simply because they are familiar.'],
      ['Plan continuation bias', 'Failing to notice that a plan is now outdated.'],
      ['Semmelweis reflex', 'Rejecting evidence that contradicts an established paradigm.'],
      ['Shared information bias', 'Discussing what everyone already knows over new facts.'],
      ['Status quo bias', 'Preferring that things stay the same.'],
      ['Well travelled road effect', 'Underestimating time on familiar routes.'],
      ['Present bias', 'Weighting payoffs more heavily as they grow nearer.'],
      ['Reactance', 'The urge to do the opposite of what someone wants you to.'],
      ['Effort justification', 'Valuing outcomes more when they took effort.'],
      ['IKEA effect', 'Overvaluing things you assembled yourself.'],
      ['Law of the instrument', 'Over-relying on a familiar tool or method.'],
      ['Not invented here', 'Aversion to ideas or products developed elsewhere.'],
      ['Reactive devaluation', 'Devaluing a proposal because it came from an adversary.'],
      ['Social comparison bias', 'Favouring candidates who don’t compete with your strengths.'],
    ],
  },
  {
    name: 'Hypothesis assessment',
    biases: [
      ['Agent detection bias', 'Presuming a sentient hand behind events.'],
      ['Availability cascade', 'A belief gaining traction through collective repetition.'],
      ['Cognitive dissonance', 'The mental toll of holding contradictory ideas.'],
      ['Common source bias', 'Combining research drawn from the same sources or methods.'],
      ['False priors', 'Initial beliefs interfering with unbiased evaluation.'],
      ['Fluency heuristic', 'Inferring higher value from easily processed information.'],
      ['Groupthink', 'Desire for harmony producing irrational group decisions.'],
      ['Groupshift', 'Group decisions being more extreme than individual ones.'],
      ['Illusion of explanatory depth', 'Believing you understand something better than you do.'],
      ['Illusory truth effect', 'Believing statements more after repeated exposure.'],
      ['Probability matching', 'Sub-optimally matching choices to reward probabilities.'],
      ['Rhyme as reason effect', 'Perceiving rhyming statements as more truthful.'],
      ['Quantification bias', 'Weighting measurable metrics over unquantifiable ones.'],
      ['Salience bias', 'Focusing on striking items while ignoring the unremarkable.'],
      ['Saying is believing effect', 'Mistaking a tuned message for your own thoughts.'],
      ['Selection bias', 'A sample distorted by non-random selection.'],
      ['Truth bias', 'A leaning toward believing what others communicate.'],
      ['Barnum effect', 'Rating vague personality descriptions as highly accurate.'],
      ['Belief bias', 'Judging an argument by how believable its conclusion is.'],
      ["Berkson's paradox", 'Misreading experiments involving conditional probabilities.'],
      ['Clustering illusion', 'Overestimating patterns in runs of random data.'],
      ['Confirmation bias', 'Seeking and reading information to confirm preconceptions.'],
      ['Congruence bias', 'Testing hypotheses only by direct confirmation.'],
      ['Extension neglect', 'Not sufficiently weighing sample size in assessment.'],
      ['Gender bias', 'Implicit biases that discriminate by gender.'],
      ['Illusory correlation', 'Perceiving a relationship between unrelated events.'],
      ['Information bias', 'Seeking information that cannot affect an action.'],
      ['Observer-expectancy effect', 'A researcher’s expectations unconsciously skewing results.'],
      ['Overconfidence effect', 'Excessive confidence in the accuracy of answers.'],
      ['Pareidolia', 'Perceiving meaningful patterns in vague stimuli.'],
      ['Subjective validation', 'Perceiving a statement as true because belief demands it.'],
      ['Survivorship bias', 'Concentrating on survivors and overlooking the rest.'],
      ['Unconscious bias', 'Automatically applied attitudes and stereotypes.'],
      ['Value selection bias', 'Leaning on existing numbers in unfamiliar contexts.'],
    ],
  },
  {
    name: 'Causal attribution',
    biases: [
      ['Apophenia', 'Perceiving meaningful connections among unrelated things.'],
      ['Assumed similarity bias', 'Assuming others share more of your traits than they do.'],
      ['Context neglect bias', 'Neglecting the human context of a technical challenge.'],
      ['Domain neglect bias', 'Ignoring relevant domain knowledge in cross-field problems.'],
      ['Embodiment bias', 'Attributing meaning from the body’s physical properties.'],
      ['Form function attribution bias', 'Judging a robot’s abilities from its appearance.'],
      ['G. I. Joe fallacy', 'Thinking that knowing a bias is enough to overcome it.'],
      ['Group attribution error', 'Believing an individual reflects the whole group, or vice versa.'],
      ['Hostile attribution bias', 'Reading ambiguous behaviour as hostile.'],
      ['Illusion of control', 'Overestimating one’s influence over external events.'],
      ['Intentionality bias', 'Judging actions as intentional rather than accidental.'],
      ['Just-world fallacy', 'Believing the world is fundamentally fair.'],
      ['Motonormativity', 'Treating motor-vehicle use as an unremarkable social norm.'],
      ['Plant blindness', 'Ignoring plants and failing to value them.'],
      ['Pro-innovation bias', 'Excessive optimism about an invention’s usefulness.'],
      ['Proportionality bias', 'Assuming big events must have big causes.'],
      ['Puritanical bias', 'Blaming undesirable outcomes on moral failing.'],
      ['Surrogation', 'Losing sight of the construct a measure stands for.'],
      ['System justification', 'Defending and preferring the existing arrangement.'],
      ['Teleological bias', 'Ascribing purpose to things lacking goal-directed action.'],
      ['Turkey illusion', 'Not expecting a sudden break in an established trend.'],
      ['Actor-observer bias', 'Blaming others’ character but one’s own circumstances.'],
      ['Defensive attribution hypothesis', 'Blaming people more when they seem unlike you.'],
      ['Egocentric bias', 'Recalling the past in a self-serving way.'],
      ["Experimenter's bias", 'Believing and publishing data that match expectations.'],
      ['Expectation bias', 'Disbelieving data that conflict with expectations.'],
      ['False uniqueness bias', 'Seeing oneself as more singular than is true.'],
      ['Fundamental attribution error', 'Overweighting character and underweighting situation in others.'],
      ['Ingroup bias', 'Giving preferential treatment to one’s own group.'],
      ['Objectivity illusion', 'Believing oneself more objective than others.'],
      ['Ostrich effect', 'Avoiding acknowledgment of an obviously bad situation.'],
      ['Outgroup favoritism', 'Expressing favourable attitudes toward other groups.'],
      ['Pygmalion effect', 'Others’ expectations shaping a person’s performance.'],
      ['Selective perception', 'Expectations distorting what one perceives.'],
      ['Self-serving bias', 'Claiming credit for success and blaming failure elsewhere.'],
      ['Ultimate attribution error', 'Making internal attributions about groups, not individuals.'],
    ],
  },
  {
    name: 'Recall (memory)',
    biases: [
      ['Boundary extension', 'Remembering a scene’s background as larger than it was.'],
      ['Childhood amnesia', 'Retaining few memories from before age four.'],
      ['Consistency bias', 'Remembering past attitudes as resembling present ones.'],
      ['Contrast effect', 'Perception enhanced or reduced versus a recent comparison.'],
      ['Cryptomnesia', 'Mistaking a memory for a novel thought.'],
      ['Cue-dependent forgetting', 'Failing to retrieve memory without the right cue.'],
      ['Google effect', 'Forgetting information easily found online.'],
      ['Duration neglect', 'Neglecting how long an episode lasted when valuing it.'],
      ['Fading affect bias', 'Bad memories’ emotions fading faster than good ones.'],
      ['False memory', 'Mistaking imagination for memory.'],
      ['Humor effect', 'Humorous items being remembered more readily.'],
      ['Implicit association', 'Word-matching speed depending on association strength.'],
      ['Lag effect', 'Learning more from spaced-out study sessions.'],
      ['Levels-of-processing effect', 'Different encoding methods varying in effectiveness.'],
      ['Leveling and sharpening', 'Memory distortions from lost detail or exaggeration.'],
      ['Memory inhibition', 'Retrieving some items making others harder to recall.'],
      ['Misinformation effect', 'Memory degraded by post-event information.'],
      ['Modality effect', 'Recalling spoken lists better than written ones.'],
      ['Repetition blindness', 'Difficulty noticing a repeated item in a sequence.'],
      ['Mood-congruent memory bias', 'Recalling information that matches your mood.'],
      ['Next-in-line effect', 'Poor recall of the speaker just before you.'],
      ['Part-list cueing effect', 'Shown items making the rest harder to recall.'],
      ['Peak–end rule', 'Judging an experience by its peak and its end.'],
      ['Persistence', 'Unwanted recurrence of traumatic memories.'],
      ['Perky effect', 'Real images influencing imagined ones, or vice versa.'],
      ['Picture superiority effect', 'Pictures being recalled more than words.'],
      ['Positivity effect', 'Older adults favouring good memories over bad.'],
      ['Processing difficulty effect', 'Harder-processed information being remembered more.'],
      ['Reminiscence bump', 'Recalling more events from adolescence and early adulthood.'],
      ['Social cryptomnesia', 'Forgetting the origins of a societal change.'],
      ['Source confusion', 'Confusing the source of a memory.'],
      ['Spacing effect', 'Better recall from spread-out exposure.'],
      ['Suffix effect', 'A trailing sound weakening the recency effect.'],
      ['Suggestibility', 'Mistaking a questioner’s suggestion for a memory.'],
      ['Telescoping effect', 'Displacing recent events back and remote events forward.'],
      ['Testing effect', 'Recalling information better by retrieving than rereading.'],
      ['Tip of the tongue', 'Recalling part of an item but not the whole.'],
      ['Verbatim effect', 'Remembering the gist better than the exact wording.'],
      ['Zeigarnik effect', 'Remembering unfinished tasks better than finished ones.'],
      ['Bizarreness effect', 'Bizarre material being remembered better than common.'],
      ['Frequency illusion', 'Noticing a thing then believing it’s suddenly everywhere.'],
      ['Baader–Meinhof phenomenon', 'Newly noticed things seeming to recur improbably often.'],
      ['List-length effect', 'Longer lists yielding a smaller percentage recalled.'],
      ['Negativity bias', 'Recalling unpleasant memories better than pleasant ones.'],
      ['Primacy effect', 'Recalling the start of a list more easily.'],
      ['Recency effect', 'Recalling the end of a list more easily.'],
      ['Serial position effect', 'Recalling the ends of a list better than the middle.'],
      ['von Restorff effect', 'A distinctive item being remembered over the rest.'],
      ['Attentional bias', 'Perception shaped by recurring thoughts.'],
      ['Continued influence effect', 'Misinformation lingering despite correction.'],
      ['Stereotype bias', 'Memory distorted toward stereotypes.'],
      ['Choice-supportive bias', 'Remembering one’s choices as better than they were.'],
      ['Declinism', 'Viewing the past favourably and the future poorly.'],
      ['Euphoric recall', 'Remembering past experiences as overly positive.'],
      ['Hindsight bias', 'Seeing past events as having been predictable.'],
      ['Recency illusion', 'Believing a newly noticed thing is itself recent.'],
      ['Recency bias', 'Favouring recent events over historic ones.'],
      ['Rosy retrospection', 'Remembering the past as better than it was.'],
      ['Cross-race effect', 'Difficulty telling apart members of another race.'],
      ['Gender differences in eyewitness memory', 'Recalling more details about one’s own gender.'],
      ['Generation effect', 'Self-generated information being recalled best.'],
      ['Placement bias', 'Remembering oneself as above average at most tasks.'],
      ['Self-relevance effect', 'Memories tied to the self being recalled best.'],
    ],
  },
  {
    name: 'Opinion reporting',
    biases: [
      ['Halo effect', 'One good trait spilling over to colour all others.'],
      ['Moral credential effect', 'Doing good giving licence to be less good later.'],
      ['Backfire effect', 'Strengthening a belief in response to disconfirming evidence.'],
      ['End-of-history illusion', 'Believing you’ll change far less in future than you have.'],
      ['Omission bias', 'Judging harmful action as worse than equally harmful inaction.'],
      ['Bandwagon effect', 'Believing things because many others do.'],
      ['Courtesy bias', 'Giving a socially acceptable opinion to avoid offence.'],
      ['Illusion of learning', 'Mistaking exposure for genuine understanding.'],
      ['Moral luck', 'Assigning moral standing based on outcomes beyond control.'],
      ['Misinterpreted-effort hypothesis', 'Reading effort as a sign of poor learning.'],
      ['Social desirability bias', 'Over-reporting desirable and under-reporting undesirable traits.'],
      ['Stereotyping', 'Expecting a group member to have certain characteristics.'],
      ['Women are wonderful effect', 'Associating more good attributes with women.'],
      ['Anthropocentric thinking', 'Using human analogies for unfamiliar biology.'],
      ['Anthropomorphism', 'Granting animals or objects human traits.'],
      ['Ben Franklin effect', 'Doing someone a favour making you like them more.'],
      ['Bias blind spot', 'Seeing oneself as less biased than others.'],
      ['Illusion of asymmetric insight', 'Believing you know peers better than they know you.'],
      ['Illusory superiority', 'Overestimating one’s desirable qualities.'],
      ['Impostor syndrome', 'Doubting accomplishments and fearing exposure as a fraud.'],
      ['Naïve realism', 'Believing you perceive reality objectively, without bias.'],
      ['Third-person effect', 'Believing media affects others more than yourself.'],
      ['Trait ascription bias', 'Seeing yourself as variable but others as predictable.'],
      ['Zero-sum bias', 'Wrongly seeing a situation as zero-sum.'],
    ],
  },
]

const slugify = (s: string) =>
  s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')

// Build categories, dropping any duplicate bias names across the whole list.
const seen = new Set<string>()
export const CATEGORIES: Category[] = RAW.map((cat) => ({
  name: cat.name,
  biases: cat.biases
    .map(([name, description]) => ({ id: slugify(name), name, description }))
    .filter((b) => {
      if (seen.has(b.id)) return false
      seen.add(b.id)
      return true
    }),
}))

export const TOTAL_BIASES = CATEGORIES.reduce((n, c) => n + c.biases.length, 0)
