export interface BlogFrontmatter {
  title: string
  description: string
  date: string
  tags: string[]
  /**
   * Authored in folio-sealed. When true the body is encrypted into
   * public/blog-enc/ and only the fields above are published.
   */
  sealed?: boolean
}

export interface BlogPostMeta extends BlogFrontmatter {
  slug: string
  tagSlugs: string[]
  sealed: boolean
}

export interface BlogPost extends BlogPostMeta {
  /** Always empty for sealed posts — their body never enters this repository. */
  content: string
}

/** Shape of src/content/stubs/<slug>.json, generated by scripts/blog-publish.ts. */
export interface BlogStubFile {
  slug: string
  title: string
  description: string
  date: string
  tags: string[]
}

/**
 * public/blog-enc/index.json. Lock ids are already public in each sealed
 * artifact, so listing them together leaks nothing new — it just lets a reader
 * discover everything their key opens in one request.
 */
export interface SealedIndex {
  v: number
  posts: Array<{ slug: string; lids: string[] }>
}

export interface BlogTag {
  label: string
  slug: string
  count: number
}

export interface BlogDataSnapshot {
  posts: BlogPost[]
  postMeta: BlogPostMeta[]
  tags: BlogTag[]
}

export interface RawBlogSource {
  fileName: string
  source: string
}
