name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-lates
    steps:
      - name: Checkout
        uses: actions/checkout@v4
   
      - name: Build
        run: |
          npm i
          npm run lint
          npm run build
          touch out/.nojekyll
   
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out # The folder the action should deploy.